### ISSUE TITLE
node issue

### ISSUE THREAD

**Issue by sherryRepro** [mondaycom/welcome-apps#115]
Error: error:0308010C:digital envelope routines::unsupported
[0]     at new Hash (node:internal/crypto/hash:79:19)
[0]     at Object.createHash (node:crypto:139:10)
[0]     at module.exports (C:\Users\SherryHuang\OneDrive - Center for Reproductive Rights\Documents\GitHub\welcome-apps\apps\quickstart-react\node_modules\webpack\lib\util\createHash.js:135:53)
[0]     at NormalModule._initBuildHash (C:\Users\SherryHuang\OneDrive - Center for Reproductive Rights\Documents\GitHub\welcome-apps\apps\quickstart-react\node_modules\webpack\lib\NormalModule.js:417:16)
[0]     at handleParseError (C:\Users\SherryHuang\OneDrive - Center for Reproductive Rights\Documents\GitHub\welcome-apps\apps\quickstart-react\node_modules\webpack\lib\NormalModule.js:471:10)
[0]     at C:\Users\SherryHuang\OneDrive - Center for Reproductive Rights\Documents\GitHub\welcome-apps\apps\quickstart-react\node_modules\webpack\lib\NormalModule.js:503:5
[0]     at C:\Users\SherryHuang\OneDrive - Center for Reproductive Rights\Documents\GitHub\welcome-apps\apps\quickstart-react\node_modules\webpack\lib\NormalModule.js:358:12
[0]     at C:\Users\SherryHuang\OneDrive - Center for Reproductive Rights\Documents\GitHub\welcome-apps\apps\quickstart-react\node_modules\loader-runner\lib\LoaderRunner.js:373:3
[0]     at iterateNormalLoaders (C:\Users\SherryHuang\OneDrive - Center for Reproductive Rights\Documents\GitHub\welcome-apps\apps\quickstart-react\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
[0]     at iterateNormalLoaders (C:\Users\SherryHuang\OneDrive - Center for Reproductive Rights\Documents\GitHub\welcome-apps\apps\quickstart-react\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
[0] C:\Users\SherryHuang\OneDrive - Center for Reproductive Rights\Documents\GitHub\welcome-apps\apps\quickstart-react\node_modules\react-scripts\scripts\start.js:19
[0]   throw err;
[0]   ^
[0]
[0] Error: error:0308010C:digital envelope routines::unsupported
[0]     at new Hash (node:internal/crypto/hash:79:19)
[0]     at Object.createHash (node:crypto:139:10)
[0]     at module.exports (C:\Users\SherryHuang\OneDrive - Center for Reproductive Rights\Documents\GitHub\welcome-apps\apps\quickstart-react\node_modules\webpack\lib\util\createHash.js:135:53)
[0]     at NormalModule._initBuildHash (C:\Users\SherryHuang\OneDrive - Center for Reproductive Rights\Documents\GitHub\welcome-apps\apps\quickstart-react\node_modules\webpack\lib\NormalModule.js:417:16)
[0]     at C:\Users\SherryHuang\OneDrive - Center for Reproductive Rights\Documents\GitHub\welcome-apps\apps\quickstart-react\node_modules\webpack\lib\NormalModule.js:452:10
[0]     at C:\Users\SherryHuang\OneDrive - Center for Reproductive Rights\Documents\GitHub\welcome-apps\apps\quickstart-react\node_modules\webpack\lib\NormalModule.js:323:13
[0]     at C:\Users\SherryHuang\OneDrive - Center for Reproductive Rights\Documents\GitHub\welcome-apps\apps\quickstart-react\node_modules\loader-runner\lib\LoaderRunner.js:367:11
[0]     at C:\Users\SherryHuang\OneDrive - Center for Reproductive Rights\Documents\GitHub\welcome-apps\apps\quickstart-react\node_modules\loader-runner\lib\LoaderRunner.js:233:18
[0]     at context.callback (C:\Users\SherryHuang\OneDrive - Center for Reproductive Rights\Documents\GitHub\welcome-apps\apps\quickstart-react\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
[0]     at C:\Users\SherryHuang\OneDrive - Center for Reproductive Rights\Documents\GitHub\welcome-apps\apps\quickstart-react\node_modules\babel-loader\lib\index.js:59:103 {
[0]   opensslErrorStack: [
[0]     'error:03000086:digital envelope routines::initialization error',
[0]     'error:0308010C:digital envelope routines::unsupported'
[0]   ],
[0]   library: 'digital envelope routines',
[0]   reason: 'unsupported',
[0]   code: 'ERR_OSSL_EVP_UNSUPPORTED'
[0] }
[0]
[0] Node.js v20.16.0
[0] npm run server exited with code 1

**Comment by yuhgto** [comment]
@sherryRepro could not reproduce this, though brief search shows this is a known issue in some versions of Webpack. 

If it's still occurring, please open a new issue with steps to reproduce and we'll fix it
